import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-container": "#2bb1b1",
        "surface-container-high": "#dce9ff",
        "primary": "#006a6a",
        "error": "#ba1a1a",
        "inverse-primary": "#5fd8d8",
        "secondary-fixed-dim": "#b8caca",
        "error-container": "#ffdad6",
        "on-primary-fixed": "#002020",
        "tertiary": "#95491c",
        "surface-container-low": "#eff4ff",
        "surface-container-lowest": "#ffffff",
        "secondary-container": "#d4e6e6",
        "on-primary-container": "#003e3e",
        "surface": "#f8f9ff",
        "on-secondary-fixed": "#0e1e1f",
        "surface-dim": "#cbdbf5",
        "on-tertiary-fixed-variant": "#773205",
        "on-tertiary-container": "#5f2500",
        "on-primary-fixed-variant": "#004f50",
        "on-error-container": "#93000a",
        "outline-variant": "#bcc9c8",
        "on-tertiary": "#ffffff",
        "on-secondary": "#ffffff",
        "on-background": "#0b1c30",
        "background": "#f8f9ff",
        "surface-container": "#e5eeff",
        "tertiary-container": "#e58856",
        "outline": "#6d7a79",
        "on-surface-variant": "#3d4949",
        "on-secondary-fixed-variant": "#3a4a4a",
        "tertiary-fixed-dim": "#ffb691",
        "secondary": "#516162",
        "on-primary": "#ffffff",
        "tertiary-fixed": "#ffdbcb",
        "on-secondary-container": "#576768",
        "surface-bright": "#f8f9ff",
        "primary-fixed-dim": "#5fd8d8",
        "inverse-surface": "#213145",
        "secondary-fixed": "#d4e6e6",
        "inverse-on-surface": "#eaf1ff",
        "on-tertiary-fixed": "#341100",
        "on-surface": "#0b1c30",
        "surface-container-highest": "#d3e4fe",
        "on-error": "#ffffff",
        "primary-fixed": "#7ef5f5",
        "surface-variant": "#d3e4fe",
        "surface-tint": "#006a6a"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "md": "1.5rem",
        "container-max": "1280px",
        "gutter": "24px",
        "xs": "0.5rem",
        "lg": "2.5rem",
        "unit": "4px",
        "sm": "1rem",
        "xl": "4rem"
      },
      fontFamily: {
        "body-md": ["Manrope", "sans-serif"],
        "label-sm": ["Manrope", "sans-serif"],
        "body-lg": ["Manrope", "sans-serif"],
        "display-lg": ["Manrope", "sans-serif"],
        "headline-sm": ["Manrope", "sans-serif"],
        "headline-md": ["Manrope", "sans-serif"],
        "label-md": ["Manrope", "sans-serif"],
        "manrope": ["Manrope", "sans-serif"],
      },
    },
  },
  plugins: [],
};
export default config;
